### ISSUE TITLE
这个文件报告解析错误

### ISSUE THREAD

**Issue by reallychenchi** [panhongwei/TraceReader#7]
此文件是通过Android monitor生成的，在temp目录下找到，可以通过monitor打开，但是用Trace Reader解析报错
[ddms4727771339660480071.zip](https://github.com/panhongwei/TraceReader/files/2327871/ddms4727771339660480071.zip)

**Comment by panhongwei** [comment]
试试换个手机呢？可能是这个生成trace的手机版本比较高，我看看代码是什么问题

**Comment by panhongwei** [comment]
更新了release里的jar包，修复了这个漏洞
